version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
    nodejs: "22"
  jobs:
    pre_build:
      - npm ci --prefix static
      - npm run build --prefix static

sphinx:
  builder: dirhtml
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements-dev.lock
