name: Release theme to PyPI

permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
    - 20*

jobs:
  build:
    name: build dist files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version: 22

    - run: npm ci
      working-directory: static

    - run: npm run build
      working-directory: static

    - uses: actions/setup-python@v6
      with:
        python-version: 3.11

    - name: install build
      run: python -m pip install --upgrade build

    - name: build dist
      run: python -m build

    - uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: dist/*
        if-no-files-found: error

  publish:
    environment:
      name: pypi-release
      url: https://pypi.org/p/shibuya

    name: release to pypi
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: artifacts
        path: dist

    - name: Push build artifacts to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  release:
    name: write release note
    runs-on: ubuntu-latest
    needs: publish

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v6
      with:
        node-version: 22
    - run: npx changelogithub --no-group
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
